version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: interdictor-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: interdictor-postgres
    environment:
      POSTGRES_USER: interdictor
      POSTGRES_PASSWORD: interdictor
      POSTGRES_DB: interdictor_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
